#!/usr/bin/env bash
set -euo pipefail

lb config noauto \
  --mode debian \
  --distribution bookworm \
  --parent-distribution bookworm \
  --parent-debian-installer-distribution bookworm \
  --architectures amd64 \
  --archive-areas "main contrib non-free non-free-firmware" \
  --parent-mirror-bootstrap http://deb.debian.org/debian \
  --parent-mirror-chroot http://deb.debian.org/debian \
  --parent-mirror-binary http://deb.debian.org/debian \
  --mirror-bootstrap http://deb.debian.org/debian \
  --mirror-chroot http://deb.debian.org/debian \
  --mirror-binary http://deb.debian.org/debian \
  --mirror-chroot-security http://security.debian.org/debian-security \
  --mirror-binary-security http://security.debian.org/debian-security \
  --debian-installer false \
  --binary-images iso-hybrid \
  --bootappend-live "boot=live components quiet splash username=myos hostname=myos" \
  --memtest none \
  --apt-indices false \
  --apt-recommends false \
  --cache true \
  --cache-packages true
